config/routes.rb
ThereWillBeBlood::Application.routes.draw do
  
	get "welcome/index"

	resources :glucose_results

  root 'welcome#index'

end

app/models/glucose_result.rb
class GlucoseResult < ActiveRecord::Base
	validates :user_id, :date_time_stamp, :result, :device, presence: true
	validates :user_id, numericality: { only_integer: true }
	validates :date_time_stamp, timeliness: { type: :datetime }
	validates :result, numericality: { only_integer: true, greater_than: 0, less_than: 5000 }
	validates :device, inclusion: { in: ["VerioIQ (meter)", "Dexcom G4 (CGM)", "Unknown"] }
	validates :notes, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/glucose_results_controller.rb
class GlucoseResultsController < ApplicationController

  def new
    # Initialise a very basic new @glucose_result instance.
		@glucose_result = GlucoseResult.new
  end

  def create
    # Assign a new instance of the "GlucoseResult" class to an @instanceVariable, passing in the relevant attributes.
		@glucose_result = GlucoseResult.new( glucose_result_params )
		@glucose_result.in_use = true
    # Save the instance (attempt to create a db record, result will determine if we were successful.)
    if @glucose_result.save
    	# Redirct to the 'show' action.
    	redirect_to @glucose_result
		else
			render 'new'
		end
  end

  def show
    # Update the @instanceVariable with the item we want to show by finding it in the db using the :id identifier.
    @glucose_result = GlucoseResult.find( params[:id] )
		if @glucose_result.in_use==false
			@glucose_result=nil
		else
			@glucose_result
		end
  end

  def index
    # Assign all existing results (that have the 'in_use' property set to true) to the @instancevariable.
    @glucose_results = GlucoseResult.where( "in_use = 't'" )
  end

  def edit
    # Find the item based on the provided :id.
    @glucose_result = GlucoseResult.find( params[:id] )
  end

  def update
    # Try to update the record.
    @glucose_result = GlucoseResult.find( params[:id] )
    # If the update works, go to the 'show' screen for that record, otherwise re-show this screen (allowing validation
    # messages be shown.)
    if @glucose_result.update( glucose_result_params )
      redirect_to @glucose_result
    else
      render 'edit'
    end
  end

  def destroy
    # Find the item based on the provided :id.
    @glucose_result = GlucoseResult.find( params[:id] )
    # Simulate destroying it by changing the 'in_use' flag.
		@glucose_result.in_use = 0
		@glucose_result.save
		# Destroy it!!!
		# @glucose_result.destroy
    # Redirect the user to an appropriate location.
    redirect_to glucose_results_path
  end

  private
    def glucose_result_params
      # "strong_parameters" requires that we define what parameters we want to accept in the controller.
			params.require( :glucose_result ) .permit( :user_id, :date_time_stamp, :result, :device, :notes )
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/glucose_results_helper.rb
module GlucoseResultsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/glucose_results/edit.html.erb
<h1>Edit Glucose Result</h1>
<p><%= link_to "Back to index", glucose_results_path %></p>
<%= form_for :glucose_result, url: glucose_result_path(@glucose_result), method: :patch do |f| %>
  <% if @glucose_result.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize( @glucose_result.errors.count, "Error" ) %> prevented this result from being saved:</h2>
			<ul>
				<% @glucose_result.errors.full_messages.each do |err_msg| %>
					<li><%= err_msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
  <p>
		<strong>User ID: </strong><%= @glucose_result.user_id %>
	</p>
	<p>
		<strong>Date/time: </strong><%= @glucose_result.date_time_stamp %>
	</p>
	<p>
		<%= f.label :result %><br>
		<%= f.text_field :result %>
	</p>
	<p>
		<%= f.label :device %><br>
		<%= f.text_field :device %>
	</p>
	<p>
		<%= f.label :notes %><br>
		<%= f.text_area :notes %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/glucose_results/index.html.erb
<h1>Listing Results</h1>
<p><%= link_to "New glucose result", new_glucose_result_path %></p>
<% if !@glucose_results.nil? %>
  <table class='gr-table'>
    <tr>
      <th></th>
      <th>Date/time</th>
      <th>Reading</th>
      <th>Source</th>
      <th>Notes</th>
      <th></th>
    </tr>
		<% i = 0 %>
    <% @glucose_results.each do |gr| %>
      <tr>
				<% styleClass = (i.even?) ? "gr-dark" : "gr-light" %>
				<td class='gr-dark'><%= gr.id %></td>
				<td class='<%= styleClass %>'><%= gr.date_time_stamp %></td>
        <td class='<%= styleClass %>'><%= gr.result %></td>
        <td class='<%= styleClass %>'><%= gr.device %></td>
        <td class='<%= styleClass %>'><%= gr.notes %></td>
        <td class='<%= styleClass %>'><%= link_to( image_tag( "/assets/images/view_icon.png", size: "14", alt: "View result" ), glucose_result_path( gr.id ) ) %>&nbsp;&nbsp;<%= link_to( image_tag( "/assets/images/edit_icon.png", size: '14', alt: "Edit result" ), edit_glucose_result_path( gr.id ) ) %>&nbsp;&nbsp;<%= link_to( image_tag( "/assets/images/del_icon.png", size: "14", alt: "Delete result" ), glucose_result_path( gr.id ), method: :delete, data: { confirm: "Are you sure?" } ) %></td>
	    </tr>
			<% i += 1 %>
    <% end %>
  </table>
<% else %>
  <p>There are no results to display.</p>
<% end %>

app/views/glucose_results/new.html.erb
<h1>New Glucose Result</h1>
<p><%= link_to "Back to index", glucose_results_path %></p>
<%= form_for :glucose_result, url: glucose_results_path do |f| %>
	<% if @glucose_result.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize( @glucose_result.errors.count, "error" ) %> prevented this result from being saved:</h2>
		<ul>
			<% @glucose_result.errors.full_messages.each do |err_msg| %>
				<li><%= err_msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<p>
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </p>
  <p>
    <%= f.label :date_time_stamp %><br>
    <%= f.text_field :date_time_stamp %>
  </p>
  <p>
    <%= f.label :result %><br>
    <%= f.text_field :result %>
  </p>
  <p>
    <%= f.label :device %><br>
    <%= f.text_field :device %>
  </p>
  <p>
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/glucose_results/show.html.erb
<h1>Glucose Result</h1>
<p><%= link_to "Back to index", glucose_results_path %> :|: <%= link_to "New glucose result", new_glucose_result_path %></p>
<p>
  <strong>User ID: </strong>
  <%= @glucose_result.user_id %>
</p>
<p>
  <strong>Date/Time: </strong>
  <%= @glucose_result.date_time_stamp.to_s %>
</p>
<p>
  <strong>Result: </strong>
  <%= @glucose_result.result.to_s %>
</p>
<p>
  <strong>Source: </strong>
  <%= @glucose_result.device %>
</p>
<p>
  <strong>Notes: </strong>
  <%= @glucose_result.notes %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThereWillBeBlood</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<div class="header-container">
			<span class="helper"></span><a href="/" id="logo"><img src="/assets/images/logo.png" height="39" width="260" alt="thereWillBeBlood" /></a><%= link_to "Glucose results", glucose_results_path %> :|: <a href="/">Visualizations</a> :|: <a href="/">Preferences</a> :|: <a href="/">Sign out</a>
		</div>
	</header>
	<div class="page-container">

<%= yield %>

	</div>
	<footer>
		<div class="footer-container">
			<a href="http://www.dexcom.com" target="_blank">Dexcom</a> :|: <a href="http://www.tandemdiabetes.com" target="_blank">Tandem Diabetes</a>
		</div>
	</footer>
</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to thereWillBeBlood</h1>
<p>Please &lt;&lt;login&gt;&gt; to begin.</p>